# This file is required to configure ToolHive Operator release information for ODH/RHOAI Operator
releases:
  - name: ToolHive Operator
    version: v0.6.8
    repoUrl: https://github.com/stacklok/toolhive
  - name: ToolHive Proxy Runner
    version: v0.6.8
    repoUrl: https://github.com/stacklok/toolhive
  - name: ToolHive Registry API
    version: v0.3.1
    repoUrl: https://github.com/stacklok/toolhive-registry-server
